### ISSUE TITLE
SqlCommand does not contain a definition for 'CommandTimeout'

### ISSUE THREAD

**Issue by mkilinskidev** [IT-integro/IntDataMigrationTool#12]
Po sklonowaniu repozytorium wraz z załączoną dll Microsoft.Data.SqlClient występuje błąd jak w tytule.
Podejżewam, że w Waszym przypadku kompilator używa innej dll, niż ta załączona w .netpackages.

![image](https://github.com/user-attachments/assets/c4a3f1a1-265a-4f7a-8591-06c37b4085c7)

**Comment by PawelBartos-Integro** [comment]
Sprawdziłem - wszystko jest O.K. 
Należy dodać plik settings.json ze wskazaniem na ścieżki plików dll
![image](https://github.com/user-attachments/assets/2f2279d7-be10-4aec-bed5-4ed61a6fbb7a)
